### PR TITLE
Added contributing info

### PR DESCRIPTION
**Pull request by Chriton**
- [added contributing info](https://github.com/CNTRPRTY/xcpdev/commit/2a3eed170fb9e86983a161278216aad9d4a1b97f)

### CODE REVIEW

**Comment by CNTRPRTY** [comment]
Looks good to me! @JavierCervilla you on board?

**Comment by jotapea** [comment]
Looks good to me! @JavierCervilla you on board?

**Comment by jotapea** [comment]
@Chriton lets do the following. Because as of now this repo is still a combination of backend and frontend, it makes it kind of problematic to go through the a `develop` branch first. And I don't want to add any friction in this critical urgent moment we are.

But feel free to add it to the new https://github.com/CNTRPRTY/xcpdev-next repo.

Is this ok with you?

**Comment by jotapea** [comment]
Or I'll just merge it, but know that @JavierCervilla and I won't necessarily go through the `develop` branch for now. But when all is more stable, for sure we can.

**Comment by Chriton** [comment]
Ok, but let's keep this rule in mind for the near future.  I will insist though for the new nextJS repo I am doing from scratch.

**Comment by jotapea** [comment]
Fair.

**Pull request merged**
