### PR TITLE
Tailwind css

### PR DESCRIPTION
**Pull request by Chriton**
Added tailwind css and formatted homepage.

- [added tailwind and tremor dependencies](https://github.com/CNTRPRTY/xcpdev/commit/e424269a79c31004b3391546c064a8d414013d32)
- [added tailwind config](https://github.com/CNTRPRTY/xcpdev/commit/5c57fe38fe57ebf7b13d3a35d83ebfccfff7a6fb)
- [added txTypeBadgeColor util function](https://github.com/CNTRPRTY/xcpdev/commit/7399d36bef7722d8a9d7bb0962122eebbc7701e0)
- [styled homepage](https://github.com/CNTRPRTY/xcpdev/commit/acd51fb72e2c539f845303812bcca0fcc24d8ac4)

### CODE REVIEW

**Comment by CNTRPRTY** [comment]
Thank you very much for this effort!

Running it locally, and I am very pleased with the initial results.

Before giving you more detailed feedback, I would suggest working on the block page in addition to the home. Want to see how you work with the [createLinkElementBindings](https://github.com/CNTRPRTY/xcpdev/blob/0ffba5d2c7df514757b0a4032c89fc57b1cc7977/src/routes/shared/elements.js#L13), because the clear visibility of what are navigation links is fundamental in the expected user experience of the application.

**Comment by jotapea** [comment]
Thank you very much for this effort!

Running it locally, and I am very pleased with the initial results.

Before giving you more detailed feedback, I would suggest working on the block page in addition to the home. Want to see how you work with the [createLinkElementBindings](https://github.com/CNTRPRTY/xcpdev/blob/0ffba5d2c7df514757b0a4032c89fc57b1cc7977/src/routes/shared/elements.js#L13), because the clear visibility of what are navigation links is fundamental in the expected user experience of the application.

**Comment by Chriton** [comment]
> Thank you very much for this effort!
> 
> Running it locally, and I am very pleased with the initial results.
> 
> Before giving you more detailed feedback, I would suggest working on the block page in addition to the home. Want to see how you work with the [createLinkElementBindings](https://github.com/CNTRPRTY/xcpdev/blob/0ffba5d2c7df514757b0a4032c89fc57b1cc7977/src/routes/shared/elements.js#L13), because the clear visibility of what are navigation links is fundamental in the expected user experience of the application.

This is an incremental approach. The purpose of this one was to add tailwind. 
The following pull requests will be made with the develop branch which I just created.

**Comment by jotapea** [comment]
Ok then lets merge it!

**Pull request merged**
